spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/pethouse
    username: root
    password: test
pethouse:
  mail-sender:
    api-url: -
    api-username: api
    api-key: -
    mail-sender: Barış Aslan <admin@barisaslan.com>
